CUDA_VISIBLE_DEVICES=4 python ./collect_diffusion_data.py \
    --env maze2d-large-v1 \
    --device 'cuda' \
    --checkpoint_dir '/workspace/ldcq/ldcq/checkpoints/contrastive-maze2d-large-30' \
    --dataset_dir '/workspace/ldcq/ldcq/data/contrastive-maze2d-large-30' \
    --skill_model_filename 'maze2d-large-v1_H_30_adist_softmax_use_contrastive_1_num_categorical_interval_10_contrastive_ratio_0.1_getrewards_1_appendgoals_0_best.pth' \
    --batch_size 1024 \
    --append_goals 0 \
    --save_z_dist 0 \
    --get_rewards 1 \
    --stride 1 \
    --beta 0.1 \
    --a_dist softmax\
    --encoder_type gru\
    --state_decoder_type mlp\
    --policy_decoder_type autoregressive\
    --per_element_sigma 1\
    --conditional_prior 1\
    --train_diffusion_prior 0\
    --h_dim 256\
    --z_dim 16\
    --use_contrastive 1 \
    --contrastive_ratio 0.1 \
    --num_categorical_interval 10 \
    --horizon 30
